---
- hosts: all
  become: true
  
  tasks:
  - name: install jdk
    yum:
      name: /tmp/jdk-8u112-linux-x64.rpm

  - name: set JAVA_HOME
    lineinfile: >
      dest=~/.bash_profile
      line='export JAVA_HOME="/usr/java/jdk1.8.0_112"'

  - name: set PATH
    lineinfile: >
      dest=~/.bash_profile
      line='export PATH="$JAVA_HOME/bin:$PATH"'