---
- hosts: data-nodes[0]
  become: true

  tasks:

  - name: post param
    uri:
      url: http://localhost:9200/_template/template_base
      method: PUT
      body: {"template" : "*", "order" : 0, "settings" : {"number_of_shards" : "{{shards}}","number_of_replicas" : "{{replicas}}"}}
      body_format: json
