---
- hosts: all
  become: true

  tasks: 
    - iptables:
        chain: IN_public_allow
        source: XXX.XXX.XXX.224/27
        destination_port: 9200
        jump: ACCEPT
        protocol: tcp

    - iptables:
        chain: IN_public_allow
        source: XXX.XXX.XXX.224/27
        destination_port: 9300
        jump: ACCEPT
        protocol: tcp
