---
- hosts: all
  become: true
  
  tasks:

  - name: set -Xms jvm option
    lineinfile: >
      dest=/etc/elasticsearch/jvm.options
      regexp='^-Xms.*'
      line='-Xms{{es_heap_size}}'

  - name: set -Xmx jvm option
    lineinfile: >
      dest=/etc/elasticsearch/jvm.options
      regexp='^-Xmx.*'
      line='-Xmx{{es_heap_size}}'
