#!/bin/bash

file="$1"

if [ ! ${file: -6} == ".ipynb" ] ; then
    exit 0
fi

jupyter nbsearch update-index $CONDA_DIR/etc/jupyter/jupyter_notebook_config.py ${NBSEARCHDB_UPDATE_INDEX_OPT} local $file
echo "Updated $file $?"
exit 0
